version: '3.9'
services:
  geekbang-time-web:
    image: xbf321/geekbang-time-web:latest
    container_name: geekbang-time-web
    restart: unless-stopped
    ports:
      - 7050:7050
    environment:
      # username:password@host:port/database
      - DBURL=postgres:sasasa@127.0.0.1:5432/geekbang_web