const productChapters = {
  chapters: [
    {
      source_id: 3541,
      title: "开篇词",
      article_count: 1,
      id: "3173",
    },
    {
      source_id: 3542,
      title: "基础篇",
      article_count: 3,
      id: "3174",
    },
    {
      source_id: 3543,
      title: "分析设计篇",
      article_count: 4,
      id: "3181",
    },
    {
      source_id: 3603,
      title: "解耦重构篇",
      article_count: 10,
      id: "3192",
    },
    {
      source_id: 3620,
      title: "持续交付篇",
      article_count: 5,
      id: "3208",
    },
    {
      source_id: 3638,
      title: "扩展篇",
      article_count: 4,
      id: "3226",
    },
    {
      source_id: 3655,
      title: "结束语",
      article_count: 2,
      id: "3235",
    },
  ],
  list: [
    {
      article_sharetitle: "一个App成了遗留系统，我们有啥破解之法？",
      audio_size: 11138373,
      include_audio: true,
      subtitles: [],
      had_freelyread: false,
      audio_url:
        "https://res001.geekbang.org/media/audio/f3/57/f3148baceb8975fcb7372caf8f1cff57/ld/ld.m3u8",
      chapter_id: "3173",
      ip_address: "北京",
      reading_time: 698,
      column_cover:
        "https://static001.geekbang.org/resource/image/6e/08/6e1ea915101fb45254a9c8bae293bc08.jpg",
      audio_time: "00:11:38",
      column_sku: 100525001,
      is_required: true,
      score: 11676277900,
      article_subtitle: "无",
      audio_download_url:
        "https://static001.geekbang.org/resource/audio/f3/57/f3148baceb8975fcb7372caf8f1cff57.mp3",
      id: 628651,
      article_title: "开篇词｜一个App成了遗留系统，我们有啥破解之法？",
      column_bgcolor: "#F6F7FB",
      is_video_preview: false,
      article_summary:
        "重构只是解决遗留系统问题关键的一个举措。但如果想根治遗留系统，其实是一个软件工程的问题，要多管齐下，综合“治疗”。",
      column_id: 586,
      audio_title: "黄俊彬 开篇词.MP3",
      audio_time_arr: {
        m: "11",
        s: "38",
        h: "00",
      },
      author_name: "黄俊彬",
      author_intro: "Thoughtworks 资深咨询师",
      offline: {
        file_name: "",
        download_url: "",
      },
      column_had_sub: false,
      audio_dubber: "黄俊彬",
      audio_md5: "f3148baceb8975fcb7372caf8f1cff57",
      article_could_preview: true,
      article_ctime: 1676277900,
      article_cover:
        "https://static001.geekbang.org/resource/image/57/8f/5728d72b4105ffb2fe16yy8d11ec6d8f.jpg",
    },
    {
      article_sharetitle: "初识重构：重构的类型、收益和度量",
      audio_size: 12782901,
      include_audio: true,
      subtitles: [],
      had_freelyread: false,
      audio_url: "",
      chapter_id: "3174",
      ip_address: "北京",
      reading_time: 801,
      column_cover:
        "https://static001.geekbang.org/resource/image/6e/08/6e1ea915101fb45254a9c8bae293bc08.jpg",
      audio_time: "00:13:21",
      column_sku: 100525001,
      is_required: true,
      score: 21676277960,
      article_subtitle: "无",
      audio_download_url: "",
      id: 628675,
      article_title: "01｜初识重构：重构的类型、收益和度量",
      column_bgcolor: "#F6F7FB",
      is_video_preview: false,
      article_summary:
        "重构的概念是什么？它能帮们解决哪些痛点问题？如何度量重构的收益？这节课将会解答这些疑惑。",
      column_id: 586,
      audio_title: "黄俊彬 01.mp3",
      audio_time_arr: {
        m: "13",
        s: "21",
        h: "00",
      },
      author_name: "黄俊彬",
      author_intro: "Thoughtworks 资深咨询师",
      offline: {
        file_name: "",
        download_url: "",
      },
      column_had_sub: false,
      audio_dubber: "黄俊彬",
      audio_md5: "",
      article_could_preview: false,
      article_ctime: 1676277960,
      article_cover:
        "https://static001.geekbang.org/resource/image/c5/b1/c5295d33b8db8103148ccc9474dfa3b1.jpg",
    },
    {
      article_sharetitle: "自动化测试：从0开始为一个特性覆盖自动化测试",
      audio_size: 13534347,
      include_audio: true,
      subtitles: [],
      had_freelyread: false,
      audio_url: "",
      chapter_id: "3174",
      ip_address: "北京",
      reading_time: 848,
      column_cover:
        "https://static001.geekbang.org/resource/image/6e/08/6e1ea915101fb45254a9c8bae293bc08.jpg",
      audio_time: "00:14:08",
      column_sku: 100525001,
      is_required: true,
      score: 21676278020,
      article_subtitle: "无",
      audio_download_url: "",
      id: 628728,
      article_title: "02｜自动化测试：从0开始为一个特性覆盖自动化测试",
      column_bgcolor: "#F6F7FB",
      is_video_preview: false,
      article_summary:
        "这节课我们会针对一个特性，从0开始一步一步覆盖自动化测试，带你深入感受到自动化测试的“魅力”",
      column_id: 586,
      audio_title: "黄俊彬 02.MP3",
      audio_time_arr: {
        m: "14",
        s: "08",
        h: "00",
      },
      author_name: "黄俊彬",
      author_intro: "Thoughtworks 资深咨询师",
      offline: {
        file_name: "",
        download_url: "",
      },
      column_had_sub: false,
      audio_dubber: "黄俊彬",
      audio_md5: "",
      article_could_preview: false,
      article_ctime: 1676278020,
      article_cover:
        "https://static001.geekbang.org/resource/image/d2/3d/d2604835643e1d1d369e9fbd9a9fec3d.jpg",
    },
    {
      article_sharetitle: "测试落地：三招提高遗留系统代码的可测试性",
      audio_size: 9749063,
      include_audio: true,
      subtitles: [],
      had_freelyread: false,
      audio_url: "",
      chapter_id: "3174",
      ip_address: "北京",
      reading_time: 611,
      column_cover:
        "https://static001.geekbang.org/resource/image/6e/08/6e1ea915101fb45254a9c8bae293bc08.jpg",
      audio_time: "00:10:11",
      column_sku: 100525001,
      is_required: true,
      score: 21676390400,
      article_subtitle: "无",
      audio_download_url: "",
      id: 629322,
      article_title: "03｜测试落地：三招提高遗留系统代码的可测试性",
      column_bgcolor: "#F6F7FB",
      is_video_preview: false,
      article_summary:
        "当我们面临一个没有任何自动化测试的遗留系统时，该如何落地自动化测试呢？",
      column_id: 586,
      audio_title: "黄俊彬 03.MP3",
      audio_time_arr: {
        m: "10",
        s: "11",
        h: "00",
      },
      author_name: "黄俊彬",
      author_intro: "Thoughtworks 资深咨询师",
      offline: {
        file_name: "",
        download_url: "",
      },
      column_had_sub: false,
      audio_dubber: "黄俊彬",
      audio_md5: "",
      article_could_preview: false,
      article_ctime: 1676390400,
      article_cover:
        "https://static001.geekbang.org/resource/image/2c/be/2c9e9f637b7de82bc28be7d5c532b4be.jpg",
    },
    {
      article_sharetitle: "架构演进：架构是如何跟随业务演进的？",
      audio_size: 11621142,
      include_audio: true,
      subtitles: [],
      had_freelyread: false,
      audio_url: "",
      chapter_id: "3181",
      ip_address: "北京",
      reading_time: 728,
      column_cover:
        "https://static001.geekbang.org/resource/image/6e/08/6e1ea915101fb45254a9c8bae293bc08.jpg",
      audio_time: "00:12:08",
      column_sku: 100525001,
      is_required: true,
      score: 31676563200,
      article_subtitle: "无",
      audio_download_url: "",
      id: 629338,
      article_title: "04｜架构演进：架构是如何跟随业务演进的？",
      column_bgcolor: "#F6F7FB",
      is_video_preview: false,
      article_summary: "要想解决遗留系统中一系列的问题，架构改造是关键的举措。",
      column_id: 586,
      audio_title: "黄俊彬 04.mp3",
      audio_time_arr: {
        m: "12",
        s: "08",
        h: "00",
      },
      author_name: "黄俊彬",
      author_intro: "Thoughtworks 资深咨询师",
      offline: {
        file_name: "",
        download_url: "",
      },
      column_had_sub: false,
      audio_dubber: "黄俊彬",
      audio_md5: "",
      article_could_preview: false,
      article_ctime: 1676563200,
      article_cover:
        "https://static001.geekbang.org/resource/image/17/58/17556254592094a6fedde939b0555a58.jpg",
    },
    {
      article_sharetitle: "项目诊断与改进：如何进行组件化分析和设计？",
      audio_size: 11876880,
      include_audio: true,
      subtitles: [],
      had_freelyread: false,
      audio_url: "",
      chapter_id: "3181",
      ip_address: "北京",
      reading_time: 744,
      column_cover:
        "https://static001.geekbang.org/resource/image/6e/08/6e1ea915101fb45254a9c8bae293bc08.jpg",
      audio_time: "00:12:24",
      column_sku: 100525001,
      is_required: true,
      score: 31676822400,
      article_subtitle: "无",
      audio_download_url: "",
      id: 630925,
      article_title: "05｜项目诊断与改进：如何进行组件化分析和设计？",
      column_bgcolor: "#F6F7FB",
      is_video_preview: false,
      article_summary:
        "通过这节课的学习，你可以了解遗留系统常见的代码、工程组织方式及其存在的问题，并掌握组件化的分析和设计思路。",
      column_id: 586,
      audio_title: "修改 黄俊彬 05.MP3",
      audio_time_arr: {
        m: "12",
        s: "24",
        h: "00",
      },
      author_name: "黄俊彬",
      author_intro: "Thoughtworks 资深咨询师",
      offline: {
        file_name: "",
        download_url: "",
      },
      column_had_sub: false,
      audio_dubber: "黄俊彬",
      audio_md5: "",
      article_could_preview: false,
      article_ctime: 1676822400,
      article_cover:
        "https://static001.geekbang.org/resource/image/e8/6e/e894ce74ef8b8fa407605183328bc86e.jpg",
    },
    {
      article_sharetitle: "分析工具：几百万行规模的遗留系统怎么分析？",
      audio_size: 9621044,
      include_audio: true,
      subtitles: [],
      had_freelyread: false,
      audio_url: "",
      chapter_id: "3181",
      ip_address: "北京",
      reading_time: 603,
      column_cover:
        "https://static001.geekbang.org/resource/image/6e/08/6e1ea915101fb45254a9c8bae293bc08.jpg",
      audio_time: "00:10:03",
      column_sku: 100525001,
      is_required: true,
      score: 31676995200,
      article_subtitle: "无",
      audio_download_url: "",
      id: 630904,
      article_title: "06｜分析工具：几百万行规模的遗留系统怎么分析？",
      column_bgcolor: "#F6F7FB",
      is_video_preview: false,
      article_summary:
        "而分析遗留系统的整体思路就是，借助自动化的工具，分析现有架构与未来架构设计的差距，梳理出需要重构的代码。",
      column_id: 586,
      audio_title: "12.19 黄俊彬 06_01.MP3",
      audio_time_arr: {
        m: "10",
        s: "03",
        h: "00",
      },
      author_name: "黄俊彬",
      author_intro: "Thoughtworks 资深咨询师",
      offline: {
        file_name: "",
        download_url: "",
      },
      column_had_sub: false,
      audio_dubber: "黄俊彬",
      audio_md5: "",
      article_could_preview: false,
      article_ctime: 1676995200,
      article_cover:
        "https://static001.geekbang.org/resource/image/71/76/71923d2f8d9d816e0756b42974a0b076.jpg",
    },
    {
      article_sharetitle: "分析实操：运用自动化工具诊断分析Sharing项目",
      audio_size: 8160993,
      include_audio: true,
      subtitles: [],
      had_freelyread: false,
      audio_url: "",
      chapter_id: "3181",
      ip_address: "北京",
      reading_time: 511,
      column_cover:
        "https://static001.geekbang.org/resource/image/6e/08/6e1ea915101fb45254a9c8bae293bc08.jpg",
      audio_time: "00:08:31",
      column_sku: 100525001,
      is_required: true,
      score: 31677168000,
      article_subtitle: "无",
      audio_download_url: "",
      id: 629359,
      article_title: "07｜分析实操：运用自动化工具诊断分析Sharing项目",
      column_bgcolor: "#F6F7FB",
      is_video_preview: false,
      article_summary:
        "通过这节课的分析，你可以学会在实际项目中如何结合工具来落地架构分析工作。",
      column_id: 586,
      audio_title: "12.20 黄俊彬 07_01.MP3",
      audio_time_arr: {
        m: "08",
        s: "31",
        h: "00",
      },
      author_name: "黄俊彬",
      author_intro: "Thoughtworks 资深咨询师",
      offline: {
        file_name: "",
        download_url: "",
      },
      column_had_sub: false,
      audio_dubber: "黄俊彬",
      audio_md5: "",
      article_could_preview: false,
      article_ctime: 1677168000,
      article_cover:
        "https://static001.geekbang.org/resource/image/6f/33/6f268859b81f003195b8cd0cee65fa33.jpg",
    },
    {
      article_sharetitle: "防微杜渐：5类遗留系统典型的代码坏味道",
      audio_size: 11204393,
      include_audio: true,
      subtitles: [],
      had_freelyread: false,
      audio_url: "",
      chapter_id: "3192",
      ip_address: "北京",
      reading_time: 702,
      column_cover:
        "https://static001.geekbang.org/resource/image/6e/08/6e1ea915101fb45254a9c8bae293bc08.jpg",
      audio_time: "00:11:42",
      column_sku: 100525001,
      is_required: true,
      score: 41677427200,
      article_subtitle: "无",
      audio_download_url: "",
      id: 632698,
      article_title: "08｜防微杜渐：5类遗留系统典型的代码坏味道",
      column_bgcolor: "#F6F7FB",
      is_video_preview: false,
      article_summary:
        "遗留系统不是一天造成的，而是在日常开发中不断累积出来的，而这五种典型的代码坏味道就是推动系统演化成遗留系统的重要元凶。",
      column_id: 586,
      audio_title: "12.20 黄俊彬 08_01.MP3",
      audio_time_arr: {
        m: "11",
        s: "42",
        h: "00",
      },
      author_name: "黄俊彬",
      author_intro: "Thoughtworks 资深咨询师",
      offline: {
        file_name: "",
        download_url: "",
      },
      column_had_sub: false,
      audio_dubber: "黄俊彬",
      audio_md5: "",
      article_could_preview: false,
      article_ctime: 1677427200,
      article_cover:
        "https://static001.geekbang.org/resource/image/9c/04/9c3e25a6e697e1290845c823d8be0e04.jpg",
    },
    {
      article_sharetitle: "重构手法：6种遗留系统常用的安全重构手法",
      audio_size: 8468322,
      include_audio: true,
      subtitles: [],
      had_freelyread: false,
      audio_url: "",
      chapter_id: "3192",
      ip_address: "北京",
      reading_time: 530,
      column_cover:
        "https://static001.geekbang.org/resource/image/6e/08/6e1ea915101fb45254a9c8bae293bc08.jpg",
      audio_time: "00:08:50",
      column_sku: 100525001,
      is_required: true,
      score: 41677600000,
      article_subtitle: "无",
      audio_download_url: "",
      id: 634205,
      article_title: "09｜重构手法：6种遗留系统常用的安全重构手法",
      column_bgcolor: "#F6F7FB",
      is_video_preview: false,
      article_summary:
        "今天我们将会学习6种遗留系统常用的安全重构手法，帮你优化代码结构，提高代码质量。",
      column_id: 586,
      audio_title: "0225  黄俊彬 09_01.MP3",
      audio_time_arr: {
        m: "08",
        s: "50",
        h: "00",
      },
      author_name: "黄俊彬",
      author_intro: "Thoughtworks 资深咨询师",
      offline: {
        file_name: "",
        download_url: "",
      },
      column_had_sub: false,
      audio_dubber: "黄俊彬",
      audio_md5: "",
      article_could_preview: false,
      article_ctime: 1677600000,
      article_cover:
        "https://static001.geekbang.org/resource/image/8d/90/8daa36d10aaab4604fbbb96d0289f490.jpg",
    },
    {
      article_sharetitle: "架构改造：5个步骤，高效推动组件化架构重构",
      audio_size: 10531530,
      include_audio: true,
      subtitles: [],
      had_freelyread: false,
      audio_url: "",
      chapter_id: "3192",
      ip_address: "北京",
      reading_time: 660,
      column_cover:
        "https://static001.geekbang.org/resource/image/6e/08/6e1ea915101fb45254a9c8bae293bc08.jpg",
      audio_time: "00:11:00",
      column_sku: 100525001,
      is_required: true,
      score: 41677772800,
      article_subtitle: "无",
      audio_download_url: "",
      id: 634298,
      article_title: "10｜架构改造：5个步骤，高效推动组件化架构重构",
      column_bgcolor: "#F6F7FB",
      is_video_preview: false,
      article_summary:
        "这节课，我们将结合实战学习4种常用的解除依赖的手法，分别是类下沉、依赖接口、事件总线以及路由。",
      column_id: 586,
      audio_title: "12.23 黄俊彬 10_01.MP3",
      audio_time_arr: {
        m: "11",
        s: "00",
        h: "00",
      },
      author_name: "黄俊彬",
      author_intro: "Thoughtworks 资深咨询师",
      offline: {
        file_name: "",
        download_url: "",
      },
      column_had_sub: false,
      audio_dubber: "黄俊彬 ",
      audio_md5: "",
      article_could_preview: false,
      article_ctime: 1677772800,
      article_cover:
        "https://static001.geekbang.org/resource/image/51/40/51debce358f7abe52f27be68189a3540.jpg",
    },
    {
      article_sharetitle: "案例演示：如何将设计最终落地到代码？",
      audio_size: 8632929,
      include_audio: true,
      subtitles: [],
      had_freelyread: false,
      audio_url: "",
      chapter_id: "3192",
      ip_address: "北京",
      reading_time: 541,
      column_cover:
        "https://static001.geekbang.org/resource/image/6e/08/6e1ea915101fb45254a9c8bae293bc08.jpg",
      audio_time: "00:09:01",
      column_sku: 100525001,
      is_required: true,
      score: 41678032000,
      article_subtitle: "无",
      audio_download_url: "",
      id: 634330,
      article_title: "11｜案例演示：如何将设计最终落地到代码？",
      column_bgcolor: "#F6F7FB",
      is_video_preview: false,
      article_summary:
        "今天我们以Sharing项目为例，结合组件化架构重构的5个步骤，最终将Sharing按新的架构设计落地到代码中。",
      column_id: 586,
      audio_title: "黄俊彬11.MP3",
      audio_time_arr: {
        m: "09",
        s: "01",
        h: "00",
      },
      author_name: "黄俊彬",
      author_intro: "Thoughtworks 资深咨询师",
      offline: {
        file_name: "",
        download_url: "",
      },
      column_had_sub: false,
      audio_dubber: " 黄俊彬",
      audio_md5: "",
      article_could_preview: false,
      article_ctime: 1678032000,
      article_cover:
        "https://static001.geekbang.org/resource/image/yy/89/yyd65112e333b135a90a0241d6f47589.jpg",
    },
    {
      article_sharetitle: "依赖注入与路由：框架能够为我们解决什么问题？",
      audio_size: 9745068,
      include_audio: true,
      subtitles: [],
      had_freelyread: false,
      audio_url: "",
      chapter_id: "3192",
      ip_address: "北京",
      reading_time: 610,
      column_cover:
        "https://static001.geekbang.org/resource/image/6e/08/6e1ea915101fb45254a9c8bae293bc08.jpg",
      audio_time: "00:10:10",
      column_sku: 100525001,
      is_required: true,
      score: 41678204800,
      article_subtitle: "无",
      audio_download_url: "",
      id: 635905,
      article_title: "12｜依赖注入与路由：框架能够为我们解决什么问题？",
      column_bgcolor: "#F6F7FB",
      is_video_preview: false,
      article_summary:
        "这节课，我将和你一起学习路由及注入框架的设计思想以及实现原理，然后结合这些框架进一步改造Sharing项目。",
      column_id: 586,
      audio_title: "12 黄俊彬_01.MP3",
      audio_time_arr: {
        m: "10",
        s: "10",
        h: "00",
      },
      author_name: "黄俊彬",
      author_intro: "Thoughtworks 资深咨询师",
      offline: {
        file_name: "",
        download_url: "",
      },
      column_had_sub: false,
      audio_dubber: "黄俊彬",
      audio_md5: "",
      article_could_preview: false,
      article_ctime: 1678204800,
      article_cover:
        "https://static001.geekbang.org/resource/image/8f/3b/8f4ea9747c18dc065679a68b1ecfe23b.jpg",
    },
    {
      article_sharetitle: "组件运行时兼容：让组件可以灵活插拔",
      audio_size: 8737596,
      include_audio: true,
      subtitles: [],
      had_freelyread: false,
      audio_url: "",
      chapter_id: "3192",
      ip_address: "北京",
      reading_time: 547,
      column_cover:
        "https://static001.geekbang.org/resource/image/6e/08/6e1ea915101fb45254a9c8bae293bc08.jpg",
      audio_time: "00:09:07",
      column_sku: 100525001,
      is_required: true,
      score: 41678377600,
      article_subtitle: "无",
      audio_download_url: "",
      id: 638406,
      article_title: "13 | 组件运行时兼容：让组件可以灵活插拔",
      column_bgcolor: "#F6F7FB",
      is_video_preview: false,
      article_summary: "只有完善组件的运行时兼容，才能真正做到组件的动态插拔。",
      column_id: 586,
      audio_title: "1.29 黄俊彬 13_01.MP3",
      audio_time_arr: {
        m: "09",
        s: "07",
        h: "00",
      },
      author_name: "黄俊彬",
      author_intro: "Thoughtworks 资深咨询师",
      offline: {
        file_name: "",
        download_url: "",
      },
      column_had_sub: false,
      audio_dubber: "黄俊彬",
      audio_md5: "",
      article_could_preview: false,
      article_ctime: 1678377600,
      article_cover:
        "https://static001.geekbang.org/resource/image/53/e0/5340f11ebbb061c7d9f25yy6420f79e0.jpg",
    },
    {
      article_sharetitle: "过大类重构：如何重构动辄过万行的一个类？",
      audio_size: 15869547,
      include_audio: true,
      subtitles: [],
      had_freelyread: false,
      audio_url: "",
      chapter_id: "3192",
      ip_address: "北京",
      reading_time: 994,
      column_cover:
        "https://static001.geekbang.org/resource/image/6e/08/6e1ea915101fb45254a9c8bae293bc08.jpg",
      audio_time: "00:16:34",
      column_sku: 100525001,
      is_required: true,
      score: 41678636800,
      article_subtitle: "无",
      audio_download_url: "",
      id: 638487,
      article_title: "14｜过大类重构：如何重构动辄过万行的一个类？",
      column_bgcolor: "#F6F7FB",
      is_video_preview: false,
      article_summary:
        "这节课，我们将一起来学习“过大类”的重构之法，让组件内分层架构重构的落地更加简单。",
      column_id: 586,
      audio_title: "1.31 黄俊彬 14_01.MP3",
      audio_time_arr: {
        m: "16",
        s: "34",
        h: "00",
      },
      author_name: "黄俊彬",
      author_intro: "Thoughtworks 资深咨询师",
      offline: {
        file_name: "",
        download_url: "",
      },
      column_had_sub: false,
      audio_dubber: "黄俊彬",
      audio_md5: "",
      article_could_preview: false,
      article_ctime: 1678636800,
      article_cover:
        "https://static001.geekbang.org/resource/image/16/d0/16de33a8231ce1eb1d974b8c676693d0.jpg",
    },
    {
      article_sharetitle: "重构实操：化整为零，落地文件模块MVP重构",
      audio_size: 11147847,
      include_audio: true,
      subtitles: [],
      had_freelyread: false,
      audio_url: "",
      chapter_id: "3192",
      ip_address: "北京",
      reading_time: 698,
      column_cover:
        "https://static001.geekbang.org/resource/image/6e/08/6e1ea915101fb45254a9c8bae293bc08.jpg",
      audio_time: "00:11:38",
      column_sku: 100525001,
      is_required: true,
      score: 41678809600,
      article_subtitle: "无",
      audio_download_url: "",
      id: 639801,
      article_title: "15 | 重构实操：化整为零，落地文件模块MVP重构",
      column_bgcolor: "#F6F7FB",
      is_video_preview: false,
      article_summary:
        "这节课，我们将按照组件内分层架构的7个步骤，重构文件模块的主页面。",
      column_id: 586,
      audio_title: "黄俊彬 15.MP3_L.mp3",
      audio_time_arr: {
        m: "11",
        s: "38",
        h: "00",
      },
      author_name: "黄俊彬",
      author_intro: "Thoughtworks 资深咨询师",
      offline: {
        file_name: "",
        download_url: "",
      },
      column_had_sub: false,
      audio_dubber: "黄俊彬",
      audio_md5: "",
      article_could_preview: false,
      article_ctime: 1678809600,
      article_cover:
        "https://static001.geekbang.org/resource/image/37/92/37yy955e01c628612af140ba017d4f92.jpg",
    },
    {
      article_sharetitle: "技术栈更新：消息组件Kotlin+MVVM重构",
      audio_size: 10019037,
      include_audio: true,
      subtitles: [],
      had_freelyread: false,
      audio_url: "",
      chapter_id: "3192",
      ip_address: "北京",
      reading_time: 628,
      column_cover:
        "https://static001.geekbang.org/resource/image/6e/08/6e1ea915101fb45254a9c8bae293bc08.jpg",
      audio_time: "00:10:28",
      column_sku: 100525001,
      is_required: true,
      score: 41678982400,
      article_subtitle: "无",
      audio_download_url: "",
      id: 640948,
      article_title: "16｜技术栈更新：消息组件Kotlin+MVVM重构",
      column_bgcolor: "#F6F7FB",
      is_video_preview: false,
      article_summary:
        "这节课我们会使用新的语言Kotlin以及新的架构模式MVVM，来重构消息组件。",
      column_id: 586,
      audio_title: "2.3 黄俊彬 16_01.MP3",
      audio_time_arr: {
        m: "10",
        s: "28",
        h: "00",
      },
      author_name: "黄俊彬",
      author_intro: "Thoughtworks 资深咨询师",
      offline: {
        file_name: "",
        download_url: "",
      },
      column_had_sub: false,
      audio_dubber: "黄俊彬",
      audio_md5: "",
      article_could_preview: false,
      article_ctime: 1678982400,
      article_cover:
        "https://static001.geekbang.org/resource/image/d3/48/d356c6fdc7bc5fa3ea23c85125b4f948.jpg",
    },
    {
      article_sharetitle: "框架升级：如何小步安全地升级数据库框架？",
      audio_size: 8708406,
      include_audio: true,
      subtitles: [],
      had_freelyread: false,
      audio_url: "",
      chapter_id: "3192",
      ip_address: "北京",
      reading_time: 546,
      column_cover:
        "https://static001.geekbang.org/resource/image/6e/08/6e1ea915101fb45254a9c8bae293bc08.jpg",
      audio_time: "00:09:06",
      column_sku: 100525001,
      is_required: true,
      score: 41679241600,
      article_subtitle: "无",
      audio_download_url: "",
      id: 640978,
      article_title: "17｜框架升级：如何小步安全地升级数据库框架？",
      column_bgcolor: "#F6F7FB",
      is_video_preview: false,
      article_summary:
        "今天我们以Sharing项目为例，一起把项目中原先采用SQL拼写的方式替换为使用Room框架来统一管理缓存数据。",
      column_id: 586,
      audio_title: "2.13 黄俊彬 17_01.MP3",
      audio_time_arr: {
        m: "09",
        s: "06",
        h: "00",
      },
      author_name: "黄俊彬",
      author_intro: "Thoughtworks 资深咨询师",
      offline: {
        file_name: "",
        download_url: "",
      },
      column_had_sub: false,
      audio_dubber: "黄俊彬",
      audio_md5: "",
      article_could_preview: false,
      article_ctime: 1679241600,
      article_cover:
        "https://static001.geekbang.org/resource/image/b1/72/b1aa1b984051b2197bc68c9c68d0bb72.jpg",
    },
    {
      article_sharetitle: "分支：是捷径还是“不归路”？",
      audio_size: 11760429,
      include_audio: true,
      subtitles: [],
      had_freelyread: false,
      audio_url: "",
      chapter_id: "3208",
      ip_address: "北京",
      reading_time: 737,
      column_cover:
        "https://static001.geekbang.org/resource/image/6e/08/6e1ea915101fb45254a9c8bae293bc08.jpg",
      audio_time: "00:12:17",
      column_sku: 100525001,
      is_required: true,
      score: 51679414400,
      article_subtitle: "无",
      audio_download_url: "",
      id: 641900,
      article_title: "18｜分支：是捷径还是“不归路”？",
      column_bgcolor: "#F6F7FB",
      is_video_preview: false,
      article_summary:
        "分支是我们日常进行开发一定会涉及到的工程实践，这节课我将为你讲解如何管理分支。",
      column_id: 586,
      audio_title: "2.23 黄俊彬 18_01.MP3",
      audio_time_arr: {
        m: "12",
        s: "17",
        h: "00",
      },
      author_name: "黄俊彬",
      author_intro: "Thoughtworks 资深咨询师",
      offline: {
        file_name: "",
        download_url: "",
      },
      column_had_sub: false,
      audio_dubber: "黄俊彬",
      audio_md5: "",
      article_could_preview: false,
      article_ctime: 1679414400,
      article_cover:
        "https://static001.geekbang.org/resource/image/15/e3/15851bc2f030ba1f6f9bd2yy49d7a0e3.jpg",
    },
    {
      article_sharetitle: "仓库&版本管理：如何从物理边界上规范依赖？",
      audio_size: 8815992,
      include_audio: true,
      subtitles: [],
      had_freelyread: false,
      audio_url: "",
      chapter_id: "3208",
      ip_address: "北京",
      reading_time: 552,
      column_cover:
        "https://static001.geekbang.org/resource/image/6e/08/6e1ea915101fb45254a9c8bae293bc08.jpg",
      audio_time: "00:09:12",
      column_sku: 100525001,
      is_required: true,
      score: 51679587200,
      article_subtitle: "无",
      audio_download_url: "",
      id: 643026,
      article_title: "19｜仓库&版本管理：如何从物理边界上规范依赖？",
      column_bgcolor: "#F6F7FB",
      is_video_preview: false,
      article_summary:
        "今天我们会学习如何对组件进行代码仓库管理以及二进制版本管理，让组件能更加独立地迭代演进，从物理上规范好组件之间的依赖。",
      column_id: 586,
      audio_title: "2.27 黄俊彬 19_01.MP3",
      audio_time_arr: {
        m: "09",
        s: "12",
        h: "00",
      },
      author_name: "黄俊彬",
      author_intro: "Thoughtworks 资深咨询师",
      offline: {
        file_name: "",
        download_url: "",
      },
      column_had_sub: false,
      audio_dubber: "黄俊彬",
      audio_md5: "",
      article_could_preview: false,
      article_ctime: 1679587200,
      article_cover:
        "https://static001.geekbang.org/resource/image/4a/78/4a23846a956dbdd35df09eb0f617d778.jpg",
    },
    {
      article_sharetitle: "20｜独立编译调试：如何让测试验证更加高效？",
      audio_size: 9313890,
      include_audio: true,
      subtitles: [],
      had_freelyread: false,
      audio_url: "",
      chapter_id: "3208",
      ip_address: "北京",
      reading_time: 583,
      column_cover:
        "https://static001.geekbang.org/resource/image/6e/08/6e1ea915101fb45254a9c8bae293bc08.jpg",
      audio_time: "00:09:43",
      column_sku: 100525001,
      is_required: true,
      score: 51679846400,
      article_subtitle: "无",
      audio_download_url: "",
      id: 643442,
      article_title: "20｜独立编译调试：如何让测试验证更加高效？",
      column_bgcolor: "#F6F7FB",
      is_video_preview: false,
      article_summary:
        "如果能够让组件独立进行编译调试，测试验证的速度就会大大提升。",
      column_id: 586,
      audio_title: "3.6 黄俊彬20_01.MP3",
      audio_time_arr: {
        m: "09",
        s: "43",
        h: "00",
      },
      author_name: "黄俊彬",
      author_intro: "Thoughtworks 资深咨询师",
      offline: {
        file_name: "",
        download_url: "",
      },
      column_had_sub: false,
      audio_dubber: "黄俊彬",
      audio_md5: "",
      article_could_preview: false,
      article_ctime: 1679846400,
      article_cover:
        "https://static001.geekbang.org/resource/image/dd/df/dd3a569a4fb005947ca7cea75bc457df.jpg",
    },
    {
      article_sharetitle: "持续集成流水线：如何通过自动化解放你的双手？",
      audio_size: 9866409,
      include_audio: true,
      subtitles: [],
      had_freelyread: false,
      audio_url: "",
      chapter_id: "3208",
      ip_address: "北京",
      reading_time: 618,
      column_cover:
        "https://static001.geekbang.org/resource/image/6e/08/6e1ea915101fb45254a9c8bae293bc08.jpg",
      audio_time: "00:10:18",
      column_sku: 100525001,
      is_required: true,
      score: 51680019200,
      article_subtitle: "无",
      audio_download_url: "",
      id: 644154,
      article_title: "21｜持续集成流水线：如何通过自动化解放你的双手？",
      column_bgcolor: "#F6F7FB",
      is_video_preview: false,
      article_summary:
        "今天，我们会以Sharing项目为例，了解如何设计、配置流水线，最后还会使用GitHub Action来搭建一个持续集成流水线。",
      column_id: 586,
      audio_title: "3.9 黄俊彬21.mp3",
      audio_time_arr: {
        m: "10",
        s: "18",
        h: "00",
      },
      author_name: "黄俊彬",
      author_intro: "Thoughtworks 资深咨询师",
      offline: {
        file_name: "",
        download_url: "",
      },
      column_had_sub: false,
      audio_dubber: "黄俊彬",
      audio_md5: "",
      article_could_preview: false,
      article_ctime: 1680019200,
      article_cover:
        "https://static001.geekbang.org/resource/image/1f/e7/1ff876e3a95cd8347f031d8435a78ee7.jpg",
    },
    {
      article_sharetitle: "22｜度量，我们如何以终为始，以始为终？",
      audio_size: 10853037,
      include_audio: true,
      subtitles: [],
      had_freelyread: false,
      audio_url: "",
      chapter_id: "3208",
      ip_address: "北京",
      reading_time: 680,
      column_cover:
        "https://static001.geekbang.org/resource/image/6e/08/6e1ea915101fb45254a9c8bae293bc08.jpg",
      audio_time: "00:11:20",
      column_sku: 100525001,
      is_required: true,
      score: 51680192000,
      article_subtitle: "无",
      audio_download_url: "",
      id: 644380,
      article_title: "22｜度量，我们如何以终为始，以始为终？",
      column_bgcolor: "#F6F7FB",
      is_video_preview: false,
      article_summary:
        "通过度量，可以让我们在研发过程中更加明确目标，避免一开始就走成了反方向。",
      column_id: 586,
      audio_title: "3.15黄俊彬 22_01.MP3",
      audio_time_arr: {
        m: "11",
        s: "20",
        h: "00",
      },
      author_name: "黄俊彬",
      author_intro: "Thoughtworks 资深咨询师",
      offline: {
        file_name: "",
        download_url: "",
      },
      column_had_sub: false,
      audio_dubber: "黄俊彬",
      audio_md5: "",
      article_could_preview: false,
      article_ctime: 1680192000,
      article_cover:
        "https://static001.geekbang.org/resource/image/71/79/719dc89b1f4b34ecf3873ca0955fe079.jpg",
    },
    {
      article_sharetitle:
        "Android系统开发：Android系统开发的版本管理、编译与自动化测试",
      audio_size: 9970665,
      include_audio: true,
      subtitles: [],
      had_freelyread: false,
      audio_url: "",
      chapter_id: "3226",
      ip_address: "北京",
      reading_time: 625,
      column_cover:
        "https://static001.geekbang.org/resource/image/6e/08/6e1ea915101fb45254a9c8bae293bc08.jpg",
      audio_time: "00:10:25",
      column_sku: 100525001,
      is_required: true,
      score: 61680451200,
      article_subtitle: "无",
      audio_download_url: "",
      id: 645221,
      article_title:
        "23｜Android系统开发：Android系统开发的版本管理、编译与自动化测试",
      column_bgcolor: "#F6F7FB",
      is_video_preview: false,
      article_summary:
        "这节课我们会学习Android系统开发的版本管理、编译调试以及相关的自动化测试等实践，了解引入这些工具及实践的目的。",
      column_id: 586,
      audio_title: "3.24 黄俊彬23_01.MP3",
      audio_time_arr: {
        m: "10",
        s: "25",
        h: "00",
      },
      author_name: "黄俊彬",
      author_intro: "Thoughtworks 资深咨询师",
      offline: {
        file_name: "",
        download_url: "",
      },
      column_had_sub: false,
      audio_dubber: "黄俊彬",
      audio_md5: "",
      article_could_preview: false,
      article_ctime: 1680451200,
      article_cover:
        "https://static001.geekbang.org/resource/image/56/9a/56d11f95c308308760f885cb46bd5a9a.jpg",
    },
    {
      article_sharetitle:
        "“魔改”的Android系统：厂商定制的Android系统为什么也要解耦？",
      audio_size: 10933518,
      include_audio: true,
      subtitles: [],
      had_freelyread: false,
      audio_url: "",
      chapter_id: "3226",
      ip_address: "北京",
      reading_time: 685,
      column_cover:
        "https://static001.geekbang.org/resource/image/6e/08/6e1ea915101fb45254a9c8bae293bc08.jpg",
      audio_time: "00:11:25",
      column_sku: 100525001,
      is_required: true,
      score: 61680624000,
      article_subtitle: "无",
      audio_download_url: "",
      id: 645699,
      article_title:
        "24｜“魔改”的Android系统：厂商定制的Android系统为什么也要解耦？",
      column_bgcolor: "#F6F7FB",
      is_video_preview: false,
      article_summary:
        "这节课，让我们聚焦在架构设计层面，看看定制系统里最容易出现哪些架构耦合问题，这些问题又会给整机产品埋下哪些隐患。",
      column_id: 586,
      audio_title: "3.24 黄俊彬 24_01.MP3",
      audio_time_arr: {
        m: "11",
        s: "25",
        h: "00",
      },
      author_name: "黄俊彬",
      author_intro: "Thoughtworks 资深咨询师",
      offline: {
        file_name: "",
        download_url: "",
      },
      column_had_sub: false,
      audio_dubber: "黄俊彬",
      audio_md5: "",
      article_could_preview: false,
      article_ctime: 1680624000,
      article_cover:
        "https://static001.geekbang.org/resource/image/b5/66/b53290217f50c259c399f8d231f24e66.jpg",
    },
    {
      article_sharetitle: "Android系统解耦：殊途同归，Android系统组件化之路",
      audio_size: 11270635,
      include_audio: true,
      subtitles: [],
      had_freelyread: false,
      audio_url: "",
      chapter_id: "3226",
      ip_address: "北京",
      reading_time: 706,
      column_cover:
        "https://static001.geekbang.org/resource/image/6e/08/6e1ea915101fb45254a9c8bae293bc08.jpg",
      audio_time: "00:11:46",
      column_sku: 100525001,
      is_required: true,
      score: 61680796800,
      article_subtitle: "无",
      audio_download_url: "",
      id: 645893,
      article_title: "25｜Android系统解耦：殊途同归，Android系统组件化之路",
      column_bgcolor: "#F6F7FB",
      is_video_preview: false,
      article_summary:
        "这节课，我们会学习整机组件化的架构设计，并探讨具体有哪些针对性的解耦策略。",
      column_id: 586,
      audio_title: "3.29 黄俊彬 25.MP3",
      audio_time_arr: {
        m: "11",
        s: "46",
        h: "00",
      },
      author_name: "黄俊彬",
      author_intro: "Thoughtworks 资深咨询师",
      offline: {
        file_name: "",
        download_url: "",
      },
      column_had_sub: false,
      audio_dubber: "黄俊彬",
      audio_md5: "",
      article_could_preview: false,
      article_ctime: 1680796800,
      article_cover:
        "https://static001.geekbang.org/resource/image/8a/cc/8afe1cbf56cf3abdbb9cbed9e1f589cc.jpg",
    },
    {
      article_sharetitle: "组件化成熟度评估，你的目的地在哪里呢？",
      audio_size: 4435407,
      include_audio: true,
      subtitles: [],
      had_freelyread: false,
      audio_url: "",
      chapter_id: "3226",
      ip_address: "北京",
      reading_time: 276,
      column_cover:
        "https://static001.geekbang.org/resource/image/6e/08/6e1ea915101fb45254a9c8bae293bc08.jpg",
      audio_time: "00:04:36",
      column_sku: 100525001,
      is_required: false,
      score: 61681056000,
      article_subtitle: "无",
      audio_download_url: "",
      id: 646568,
      article_title: "加餐｜组件化成熟度评估，你的目的地在哪里呢？",
      column_bgcolor: "#F6F7FB",
      is_video_preview: false,
      article_summary:
        "今天这期加餐内容，我想给你分享一个实用的工具——组件化成熟度模型，并以Sharing项目为例，带你一起对改进前后的项目做一次组件化成熟度评估。",
      column_id: 586,
      audio_title: "3.29 黄俊彬 26_01.MP3",
      audio_time_arr: {
        m: "04",
        s: "36",
        h: "00",
      },
      author_name: "黄俊彬",
      author_intro: "Thoughtworks 资深咨询师",
      offline: {
        file_name: "",
        download_url: "",
      },
      column_had_sub: false,
      audio_dubber: "黄俊彬",
      audio_md5: "",
      article_could_preview: false,
      article_ctime: 1681056000,
      article_cover:
        "https://static001.geekbang.org/resource/image/ca/6c/cace00af846f8ffe9955b52552e3896c.jpg",
    },
    {
      article_sharetitle: "以重构为动力，让遗留系统焕发新生",
      audio_size: 6427941,
      include_audio: true,
      subtitles: [],
      had_freelyread: false,
      audio_url: "",
      chapter_id: "3235",
      ip_address: "北京",
      reading_time: 402,
      column_cover:
        "https://static001.geekbang.org/resource/image/6e/08/6e1ea915101fb45254a9c8bae293bc08.jpg",
      audio_time: "00:06:42",
      column_sku: 100525001,
      is_required: true,
      score: 71681228800,
      article_subtitle: "无",
      audio_download_url: "",
      id: 647686,
      article_title: "结束语｜以重构为动力，让遗留系统焕发新生",
      column_bgcolor: "#F6F7FB",
      is_video_preview: false,
      article_summary:
        "系统重构的学习之旅，即将告一段落，今天，我还想和你分享三点“意识”层面的改变，这对于我们落地遗留系统改造同样重要。",
      column_id: 586,
      audio_title: "4.11黄俊彬 27_01.MP3",
      audio_time_arr: {
        m: "06",
        s: "42",
        h: "00",
      },
      author_name: "黄俊彬",
      author_intro: "Thoughtworks 资深咨询师",
      offline: {
        file_name: "",
        download_url: "",
      },
      column_had_sub: false,
      audio_dubber: "黄俊彬",
      audio_md5: "",
      article_could_preview: false,
      article_ctime: 1681228800,
      article_cover:
        "https://static001.geekbang.org/resource/image/da/bc/da6c69e4c0d4e0f910ec929333381bbc.jpg",
    },
    {
      article_subtitle: "无",
      id: 647701,
      article_title: "期末测试｜来赴一场满分之约！",
      include_audio: false,
      subtitles: [],
      had_freelyread: false,
      article_could_preview: false,
      chapter_id: "3235",
      column_had_sub: false,
      reading_time: 45,
      ip_address: "北京",
      article_cover:
        "https://static001.geekbang.org/resource/image/a9/1a/a94542d63e6707b3aebc5b5ac6574e1a.jpg",
      column_sku: 100525001,
      offline: {
        file_name: "",
        download_url: "",
      },
      is_video_preview: false,
      is_required: false,
      article_summary: "来赴一场满分之约！",
      score: 71681228800,
      article_ctime: 1681228800,
    },
  ],
};
export default productChapters;
